# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f1baea661929ef721d434c2c0f7ba9f51054ebbf0862a265578a6863df2a0a83f5a50a3b0755eb023cc57f89192b19f61dbb98aa82b7e6a0818fdcfcd2eed9e

test:
  secret_key_base: f6490cf06b19126d5e5415839b51759fdeaf4fceefcb0ef948ad08a6b712ac26d306a3b2d9dbc1b58d91f3e1cf9b19c19a833d8460ed762a491c80211eaaa3f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
